### ISSUE TITLE
Changing owner editable to true creates migration file in wagtailcore

### ISSUE THREAD

**Issue by nicklo** [APSL/puput#107]
While running makemigrations for my own apps as part of a wagtail based project I'd sporadically get the following migration file generated within _wagtail/wagtailcore/migrations/_

```python
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pages', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
```

After some assistance via http://stackoverflow.com/questions/42263389/wagtailcore-owner-alter-field-migration-being-generated-when-doing-app-makemigra it appears that the reason this was happening is the line:

`EntryPage._meta.get_field('owner').editable = True`

https://github.com/APSL/puput/blob/master/puput/models.py#L204

I'm wondering if anyone else has experienced this issue and can confirm it is the reason for the migration file being created within Wagtail's own migration files.

**Comment by marctc** [comment]
Yikes! I had this issues several times but never figure out why! The idea behind make "owner" editable is to have a owner choser while creating/editing an entry. Maybe @gasman could give us any idea how to fix this without that ugly monkey-patching.

**Comment by gasman** [comment]
I reckon we could change it to `editable=True` within Wagtail with no ill effects. The `editable=False` was necessary in early versions of Wagtail because the page editor would automatically add any 'spare' fields that weren't accounted for in the panels definition - the idea was to make the panel definition optional, but that never worked well (it just gave you an unlabelled input field outside of the tabs). It doesn't do that any more, and I don't think there are any other ModelForms elsewhere in Wagtail that include the `owner` field as standard - so changing the flag won't cause any visible change. (And, of course, if you've been successfully using this configuration in Puput with no problems up to now, that's a good indication that it's a safe thing to do...)

If you'd be willing to take a look through the Wagtail code to check that there are no occurrences of `owner` that would cause it to surface on forms, I'd be happy to accept a pull request to change this.

**Comment by uditagarwal** [comment]
Watching this thread to know when it's fixed
