### ISSUE TITLE
Extending EntryPage and Entries 

### ISSUE THREAD

**Issue by uditagarwal** [APSL/puput#108]
Hello!

Thanks for the wonderful work on this plugin. I have been using an extended EntryPage for which I have made a class and done the migrations 

```
class EntryPage:
   video_header_url = models.

...

```

It loads all fine and great on its own page where I can access 
`{{ self.video_header_url }}` 

in the template, however on the entry page for my blog, doing a

`{{ entry.video_header_url }}
`
only gives me an empty! Is there another step I have to take to get my custom EntryPage class to show up correctly on my main entries page where I do a 

`{% for entry in entries %}
`

**Comment by csalom** [comment]
Hi @uditagarwal 

How are you getting the entries list? I supose that you have done something like: BlogPage.get_children(), do you?
In this case, you have to do: entry.specific.video_header_url.

That's because the wagtail method get_children() does a query to your DataBase looking for Page Model. If you navegate inside it, you could take a look.

Then, Wagtail provides you the "specific" property to acces to your own model, where you wil find the "video_header_url" attribute.

I hope that this explanation solve your issue.

Let me know

**Comment by uditagarwal** [comment]
Alright, this works for me! Thanks a lot for your insight :)
