### ISSUE TITLE
Unable to enter code blocks

### ISSUE THREAD

**Issue by boboysdadda** [APSL/puput#166]
I am unable to enter a code block. I was going to copy the blocks.py file and add the needed code but it only comes with a .pyc.   Is there any intent of adding code block support such as https://github.com/FlipperPA/wagtailcodeblock instead of just an unformated line of code?

**Comment by MiltonLn** [comment]
Since we provide support to extending the Entry Page model, there's no need to provide built-in support for `wagtailcodeblock` or similars.

Just follow this guide to extend the Entry Page model and add your own `StreamField` for the body using `wagtailcodeblock` ;) let me know if you still need help with this.
