### ISSUE TITLE
Add wagtail 2.1 support

### ISSUE THREAD

**Issue by filippovd20** [APSL/puput#168]
Wagtail 2.1 brings a host of new features and improvements http://docs.wagtail.io/en/v2.1.1/releases/2.1.html
Puput is currently incompatible with wagtail v2.1

**Comment by lanshark** [comment]
Are you sure about that?  I have a copy of bakerydemo that I've upgraded to wagtail 2.1, with puput instead of the simple blog.  I'm not seeing any incompatibilites except the message when I pip install that the requirements don't match.  I have not tried extensive testing, but everything I've done so far seems to work.

**Comment by csalom** [comment]
Hi!
@filippovd20 Can you bee more specific about the incompabilities that you have mentioned, please?
I've testes puput with wagtail 2.1 and I didn't find any problem.

My requirements are:
* Django==2.0.1
* wagtail==2.1
* puput==1.0.2
* django-el-pagination==3.2.1
* django-social-share==1.1.2
* django-colorful==1.2

**Comment by filippovd20** [comment]
Looks like there are no real incompatibilities with wagtail 2.1 other than deafult puput requirements for wagtail 2.0. I've tested it on my project and all seems to be working fine. 
All you need to switch to v2.1 is once the package is upgraded do makemigrations and migrate new wagtail user and admin models (wagtail added avatar support in user models).

**Comment by csalom** [comment]
That's great!
The default puput's requirements have been updated in PR #169.
