### ISSUE TITLE
Django Comments are now required

### ISSUE THREAD

**Issue by loleg** [APSL/puput#222]
Currently the [setup guide](https://django-contrib-comments.readthedocs.io/en/latest/quickstart.html) or [comments chapter](https://puput.readthedocs.io/en/latest/comments.html) makes no mention of [Django Comments](https://django-contrib-comments.readthedocs.io/) - but I am getting this error from **compress**:

```
../lib/python3.7/site-packages/puput/templates/puput/comments/django_comments.html: 
'comments' is not a registered tag library
```

Adding it to my project (`django.contrib.sites` and `django_comments` in `INSTALLED_APPS`) according to the [Quick Start](https://django-contrib-comments.readthedocs.io/en/latest/quickstart.html) resolves this.

**Comment by loleg** [comment]
Adding `django.contrib.sites` breaks things (like the admin panel, ahem..) in Wagtail, so this is not a good workaround. If anyone has other ideas of how to deal with this error, please let me know.

**Comment by michalpleszczynski** [comment]
I've added an option to use django comments in #215, the documentation was updated in that PR as well, so it looks like it needs to be pushed to readthedocs? Anyway, I'll check out the error

**Comment by woesoe** [comment]
I would use the documentation of django-comments-xtd instead of django-comments if I were you. I Followed all the steps in the django-comments-xtd quick start guide (https://django-comments-xtd.readthedocs.io/en/latest/quickstart.html), added `PUPUT_COMMENTS_PROVIDER = "puput.comments.DjangoCommentsProvider"` in the Django Settings and got comments to work.

When I change `django_comments.html` like below, nested indenting doesn't work unfortunately. If anyone could help me with that it would be greatly appreciated.
```
{% load comments %}
{% load comments_xtd %}

<div>
    <h3>Comments:</h3>
    {% render_comment_form for entry %}
    {% render_xtdcomment_tree for entry%}
</div>
```
