### ISSUE TITLE
Possible roadmap

### ISSUE THREAD

**Issue by voylinux** [APSL/puput#38]
I have some ideas about things that could be added like some custom post types such as video, picture ... etc (somehow a WordPress style) and not sure if those thing should be suggested as pull requests here in this repo or just developed as Wagtail or Puput addons.

Do you have some kind of future roadmap or public discussion so people can contribute to the project?.
And if so ... how to add them according to the current default theme.

Thanks

**Comment by marctc** [comment]
>I have some ideas about things that could be added like some custom post types such as video, picture ... etc (somehow a WordPress style) and not sure if those thing should be suggested as pull requests here in this repo or just developed as Wagtail or Puput addons.

Maybe if you have an idea that could be useful not only on Puput it could be make as a Wagtail plugin and add it as Puput dependecy. Otherwise, we can add it to Puput without any trouble.

>Do you have some kind of future roadmap or public discussion so people can contribute to the project?.
And if so ... how to add them according to the current default theme.

No, we haven't (it's all in my head hehe). We can open issues here and tag it for an specific roadmap and as "enhacements". What do you think?

**Comment by voylinux** [comment]
Open issues and discuss here if you think this should be inside puput or not sounds great for me if you like the idea in having some help with the project. ;)

This way also if you have no plans to include it in the "core", I can release it as a plugin.
